#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_SINTRONIX_TS_NOKIA439)  += sitronix_ts_nokia439.o
sitronix_ts_nokia439-objs := sitronix_i2c_touch.o st143xx_RawTest.o st143xx_fw_upgrade.o
