//add for ocp2031 +-5v panel power on
typedef enum
{
	LCM_LDO_VOL_0V,

	
    	LCM_LDO_VOL_4V0,
	LCM_LDO_VOL_4V1,
	LCM_LDO_VOL_4V2,
	LCM_LDO_VOL_4V3,
	LCM_LDO_VOL_4V4,
	LCM_LDO_VOL_4V5,
	LCM_LDO_VOL_4V6,
	LCM_LDO_VOL_4V7,
	LCM_LDO_VOL_4V8,
	LCM_LDO_VOL_4V9,
	LCM_LDO_VOL_5V0,
	LCM_LDO_VOL_5V1,
	LCM_LDO_VOL_5V2,
	LCM_LDO_VOL_5V3,
	LCM_LDO_VOL_5V4,
	LCM_LDO_VOL_5V5,
	LCM_LDO_VOL_5V6,
	LCM_LDO_VOL_5V7,
	LCM_LDO_VOL_5V8,
	LCM_LDO_VOL_5V9,
	LCM_LDO_VOL_6V0,


	LCM_LDO_VOL_MAX,
}LCM_LDO_VOLTAGE_E;

//add for ocp2031 +-5v panel power on
int ocp2131_set_voltage(LCM_LDO_VOLTAGE_E avdd,LCM_LDO_VOLTAGE_E avee);
