#
# Makefile for the Goodix gt9xx touchscreen driver.
#
#subdir-ccflags-y += -DDEBUG
obj-$(CONFIG_TOUCHSCREEN_GT9XX_NOKIA439)	+= gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_UPDATE_NOKIA439)	+= gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_TOOL_NOKIA439)	+= goodix_tool.o
